# permissions for end users to view catalogentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalogentry-viewer-role
rules:
- apiGroups:
  - catalog.kcp.dev
  resources:
  - catalogentries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apis.kcp.dev
  resources:
  - catalogentries/status
  verbs:
  - get
